### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by gostik** [Piasy/AndroidTDDBootStrap#8]
Hi

When i run 
`buck install appDevDebug`

i get

> BUILD FAILED: //model:src_release failed on step javac with an exception:
java.lang.NoSuchMethodError: com.squareup.javapoet.TypeName.isBoxedPrimitive()Z
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.squareup.javapoet.TypeName.isBoxedPrimitive()Z
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:247)
        at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:155)
        at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:154)
        at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:137)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1223)
        at com.facebook.buck.rules.CachingBuildEngine.access$300(CachingBuildEngine.java:113)
        at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:304)
        at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:294)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:61)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.squareup.javapoet.TypeName.isBoxedPrimitive()Z
        at com.ryanharter.auto.value.parcel.Parcelables.isValidType(Parcelables.java:47)
        at com.ryanharter.auto.value.parcel.Parcelables.getParcelableType(Parcelables.java:63)
        at com.ryanharter.auto.value.parcel.Parcelables.isValidType(Parcelables.java:51)
        at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.validateProperties(AutoValueParcelExtension.java:210)
        at com.ryanharter.auto.value.parcel.AutoValueParcelExtension.generateClass(AutoValueParcelExtension.java:123)
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:424)
        at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:143)
        at com.facebook.buck.jvm.java.TracingProcessorWrapper.process(TracingProcessorWrapper.java:104)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 20 more

> 

Found https://github.com/rharter/auto-value-parcel/issues/64  , but it doesn't help

**Comment by gostik** [comment]
btw, `gradle build` works ok

**Comment by Piasy** [comment]
@gostik Yes, BUCK has problem with SqlDelight now.

**Comment by Piasy** [comment]
With the newest version of OkBuck, it works now.
